### ISSUE TITLE
.xcodeproj 파일이 git상에 존재하지 않습니다.

### ISSUE THREAD

**Issue by dolfalf** [wnstjd0333/calculator#2]
Fork -> clone 해서 소스를 받았는데 프로젝트가 열리지 않아요. 
보니까 .xcodeproj 파일이 없거든요. 
커밋, 푸쉬가 덜된거 같은데 확인좀 해주세요

**Comment by wnstjd0333** [comment]
레파지토리 안에 또 같은이름 폴더하고 .xcodeproj이 있어서 폴더만 따로 빼서 커밋, 푸쉬 했었어요.
.xcodeproj 커밋, 푸쉬 되었습니다.
